-- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
# FROM PRODUCT P
# JOIN OFFLINE_SALE O ON P.PRODUCT_ID AND O.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, P.PRODUCT_CODE

SELECT PRODUCT_CODE, SUM(SALES_AMOUNT*PRICE) AS SALES
FROM PRODUCT JOIN OFFLINE_SALE USING(PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE