-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MaxFavorites ON REST_INFO.FOOD_TYPE = MaxFavorites.FOOD_TYPE AND REST_INFO.FAVORITES = MaxFavorites.MAX_FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC
