-- 코드를 입력하세요
WITH NO_UPON AS(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE NOT LIKE '%Spayed%' AND SEX_UPON_INTAKE NOT LIKE '%Neutered%'
)


SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
JOIN NO_UPON USING(ANIMAL_ID)
WHERE SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE '%Neutered%'
ORDER BY ANIMAL_ID