# 자동차 종류 = 트럭
# 대여금액 계산
# 


# SELECT 
# B.HISTORY_ID, 
# CASE
#     WHEN TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1 >=90 THEN ROUND(0.90 * A.DAILY_FEE * (TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1))
#     WHEN TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1 >=30 THEN ROUND(0.93 * A.DAILY_FEE * (TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1))
#     WHEN TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1 >=7 THEN ROUND(0.95 * A.DAILY_FEE * (TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1))
#     ELSE ROUND(A.DAILY_FEE * (TIMESTAMPDIFF(DAY,B.START_DATE,B.END_DATE)+1))
# END AS FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID=B.CAR_ID
# WHERE A.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, B.HISTORY_ID DESC

SELECT HISTORY_ID,
    ROUND(DAILY_FEE * 
        CASE
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN (SELECT (1 - DISCOUNT_RATE * 0.01) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN (SELECT (1 - DISCOUNT_RATE * 0.01) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN (SELECT (1 - DISCOUNT_RATE * 0.01) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
            ELSE 1
        END
          , 0) * (DATEDIFF(END_DATE,START_DATE) + 1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;