-- 코드를 입력하세요
WITH SUB AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF 
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY 
    GROUP BY FLAVOR
    )
    
SELECT FLAVOR
FROM SUB
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3