-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역
SELECT APNT_NO, PT_NAME, PT_NO, C.MCDP_CD, C.DR_NAME, TIMESTAMP(APNT_YMD) AS APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT B USING(PT_NO)
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND C.MCDP_CD='CS'
ORDER BY APNT_YMD