SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (MaxSizes.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV,
    ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR
) AS MaxSizes ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MaxSizes.YEAR
ORDER BY YEAR, YEAR_DEV